# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "postgresql"]

[phases.install]
cmds = [
    "python -m ensurepip",
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
]

[start]
cmd = "python -m uvicorn src.main:app --host 0.0.0.0 --port ${PORT:-8000}"